import Link from "next/link"
import React from "react"

const TermsAndConditions: React.FC = () => {
  return (
    <div className="p-4 max-w-[1000px] mx-auto text-[#565656] mt-[70px] md:mt-[150px] md:text-[16px] text-sm">
      <h1 className="text-4xl font-bold mb-6 text-center text-black">
        Terms & Conditions
      </h1>
      <p className="text-center text-gray-600 mb-8">
        General terms and conditions for SwiftVia Logistics LTD
      </p>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          1. Introduction
        </h2>
        <p>
          By accessing and placing an order with SwiftVia Logistics LTD
          (&quote;SwiftVia&quote;), you confirm your agreement with and
          acceptance of the Terms of Service as outlined below. These terms
          apply to the entire website and any communication between you and
          SwiftVia, including emails.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          2. License
        </h2>
        <p>
          SwiftVia grants you a revocable, non-exclusive, non-transferable,
          limited license to download, install, and use the website/apps
          strictly by the terms of this agreement.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          3. Agreement between you and SwiftVia
        </h2>
        <p>
          These Terms & Conditions constitute a contract between you and
          SwiftVia, the provider of the SwiftVia website and services. Using the
          SwiftVia Service, you agree to be bound by these Terms & Conditions.
          If you disagree, please refrain from using the SwiftVia Service.
          &quote;You&quote; refers to both individuals and entities.
        </p>
        <h3 className="font-semibold mb-4">Meanings</h3>
        <ul className="list-disc list-inside ml-4 space-y-4">
          <li>
            <strong>Cookie:</strong> A small amount of data generated by a
            website and saved by your web browser for identification and
            analytics.
          </li>
          <li>
            <strong>Company:</strong> SwiftVia Logistics LTD, based in Lagos,
            Nigeria, is responsible for your information under these Terms &
            Conditions.
          </li>
          <li>
            <strong>Country:</strong> The location where SwiftVia or its
            owners/founders are based, in this case, Nigeria.
          </li>
          <li>
            <strong>Device:</strong> Any internet-connected device, such as a
            phone, tablet, computer, or similar, used to access SwiftVia and its
            services.
          </li>
          <li>
            <strong>Service:</strong> Refers to the Service provided by
            SwiftVia, as described in the relative terms and on this platform.
          </li>
        </ul>
      </section>

      {/* Other sections follow the same structure */}
      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          4. Restrictions
        </h2>
        <ul className="list-disc list-inside ml-4 space-y-4">
          <li>
            License, sell, rent, lease, assign, distribute, transmit, host,
            outsource, disclose, or otherwise commercially exploit the website
            or make the platform available to any third party.
          </li>
          <li>
            Modify, make derivative works of, disassemble, decrypt, reverse
            compile, or reverse engineer any part of the website.
          </li>
          <li>
            Remove, alter, or obscure any proprietary notice of SwiftVia or its
            affiliates, partners, suppliers, or licensors.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          5. Your Suggestion
        </h2>
        <p>
          Any suggestions you provide to SwiftVia regarding the website are the
          sole property of SwiftVia. SwiftVia is free to use, copy, modify,
          publish, or redistribute suggestions without providing credit or
          compensation to you.
        </p>
      </section>

      {/* Add sections 6 to 22 similarly */}

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          22. Contact Us
        </h2>
        <p>
          For questions, contact us via email at{" "}
          <Link href="mailto:contact@swiftvia.com" className="text-blue-500">
            contact@swiftvia.com
          </Link>
          .
        </p>
      </section>
    </div>
  )
}

export default TermsAndConditions
