import Link from "next/link"
import React from "react"

const TermsAndConditions: React.FC = () => {
  return (
    <div className="p-4 max-w-[1000px] mx-auto text-[#565656] mt-[70px] md:mt-[150px] md:text-[16px] text-sm">
      <h1 className="text-4xl font-bold mb-6 text-center text-black">
        Terms & Conditions
      </h1>
      <p className="text-center text-gray-600 mb-8">
        General terms and conditions for SwiftVia Logistics LTD
      </p>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          1. Introduction
        </h2>
        <p>
          By accessing and placing an order with SwiftVia Logistics LTD
          (&quot;SwiftVia&quot;), you confirm your agreement with and acceptance
          of the Terms of Service as outlined below. These terms apply to the
          entire website and any communication between you and SwiftVia,
          including emails.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          2. License
        </h2>
        <p>
          SwiftVia grants you a revocable, non-exclusive, non-transferable,
          limited license to download, install, and use the website/apps
          strictly by the terms of this agreement.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          3. Agreement between you and SwiftVia
        </h2>
        <p>
          These Terms & Conditions constitute a contract between you and
          SwiftVia, the provider of the SwiftVia website and services. Using the
          SwiftVia Service, you agree to be bound by these Terms & Conditions.
          If you disagree, please refrain from using the SwiftVia Service.
          &quot;You&quot; refers to both individuals and entities.
        </p>
        <h3 className="font-semibold mb-4">Meanings</h3>
        <ul className="list-disc list-inside ml-4 space-y-4">
          <li>
            <strong>Cookie:</strong> A small amount of data generated by a
            website and saved by your web browser for identification and
            analytics.
          </li>
          <li>
            <strong>Company:</strong> SwiftVia Logistics LTD, based in Lagos,
            Nigeria, is responsible for your information under these Terms &
            Conditions.
          </li>
          <li>
            <strong>Country:</strong> The location where SwiftVia or its
            owners/founders are based, in this case, Nigeria.
          </li>
          <li>
            <strong>Device:</strong> Any internet-connected device, such as a
            phone, tablet, computer, or similar, used to access SwiftVia and its
            services.
          </li>
          <li>
            <strong>Service:</strong> Refers to the Service provided by
            SwiftVia, as described in the relative terms and on this platform.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          4. Restrictions
        </h2>
        <ul className="list-disc list-inside ml-4 space-y-4">
          <li>
            License, sell, rent, lease, assign, distribute, transmit, host,
            outsource, disclose, or otherwise commercially exploit the website
            or make the platform available to any third party.
          </li>
          <li>
            Modify, make derivative works of, disassemble, decrypt, reverse
            compile, or reverse engineer any part of the website.
          </li>
          <li>
            Remove, alter, or obscure any proprietary notice of SwiftVia or its
            affiliates, partners, suppliers, or licensors.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          5. Your Suggestion
        </h2>
        <p>
          Any suggestions you provide to SwiftVia regarding the website are the
          sole property of SwiftVia. SwiftVia is free to use, copy, modify,
          publish, or redistribute suggestions without providing credit or
          compensation to you.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          6. Your Consent
        </h2>
        <p>
          By using our website, registering an account, or making a purchase,
          you consent to our Terms & Conditions.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          7. Links to Other Websites
        </h2>
        <p>
          These Terms & Conditions apply only to SwiftVia services. Links to
          external websites are not operated or controlled by SwiftVia. We are
          not responsible for such websites&apos; content, accuracy, or
          opinions. Your interaction with other websites is subject to their
          rules and policies.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          8. Cookies
        </h2>
        <p>
          SwiftVia uses cookies to identify visited areas of our website.
          Cookies enhance performance and functionality but are non-essential.
          Disabling cookies may affect certain functionality.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          9. Third-Party Services
        </h2>
        <p>
          SwiftVia may display third-party content or provide links to
          third-party services. SwiftVia is not responsible for the accuracy,
          completeness, or any aspect of Third-Party Services. You access them
          at your own risk and subject to their terms and conditions.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          10. Term and Termination
        </h2>
        <p>
          This agreement remains in effect until terminated by you or SwiftVia.
          SwiftVia may suspend or terminate this agreement at any time and for
          any reason, with or without notice.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          11. Limitation of Liability
        </h2>
        <p>
          SwiftVia&apos;s liability under this agreement is limited to the
          amount paid by you for the website. In no event shall SwiftVia or its
          suppliers be liable for special, incidental, indirect, or
          consequential damages.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          12. Severability
        </h2>
        <p>
          If any provision of this agreement is unenforceable, it will be
          changed to achieve its objectives to the greatest extent possible. The
          remaining provisions will continue in full force and effect.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          13. Entire Agreement
        </h2>
        <p>
          This agreement, along with the Privacy Policy and any legal notices by
          SwiftVia, constitutes the entire agreement between you and SwiftVia.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          14. Update to our Terms
        </h2>
        <p>
          We may change our Service and policies and notify you of any changes.
          Continued use of the Service implies acceptance of updated Terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          15. Intellectual Property
        </h2>
        <p>
          The website and its contents are owned by SwiftVia and are protected
          by copyright, trademark, and other intellectual property laws.
          Unauthorized use is prohibited.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          16. Notice of Dispute
        </h2>
        <p>
          In case of a dispute, a Notice of Dispute must be provided. We will
          attempt to resolve disputes through informal negotiation before
          commencing arbitration.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          17. Submission and Privacy
        </h2>
        <p>
          Submissions provided by you become the sole property of SwiftVia
          without compensation. SwiftVia has no obligations regarding submitted
          ideas.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          18. Promotion
        </h2>
        <p>
          Promotions may have separate rules, and you agree to abide by them.
          Additional terms may apply to purchases through the Services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          19. Typography Error
        </h2>
        <p>
          SwiftVia reserves the right to refuse or cancel orders with incorrect
          pricing or information due to typographical errors.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          20. Miscellaneous
        </h2>
        <p>
          The remainder of the agreement will continue if any provision is found
          unenforceable. Waivers must be in writing. SwiftVia operates from
          Nigeria, and its Service is not intended for use where prohibited by
          law.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          21. Disclaimer
        </h2>
        <p>
          SwiftVia is not responsible for content imprecisions, provides no
          warranties, and disclaims liability for damages. The Service is
          provided &quot;as is&quot; and &quot;as available.&quot;
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-lg md:text-xl text-black font-semibold mb-4">
          22. Contact Us
        </h2>
        <p>
          For questions, contact us via email at{" "}
          <Link href="mailto:contact@swiftvia.com" className="text-blue-500">
            contact@swiftvia.com
          </Link>
          .
        </p>
      </section>
    </div>
  )
}

export default TermsAndConditions
